from app.domain.enums.pruduct_unit import Unit
from app.domain.entities.product import Product


def build_products(category_map: dict, brand_map: dict) -> list[Product]:
    return [
        # FILTERS
        Product(
            sku="FIL-001",
            name="Filtro de Aceite",
            description="Filtro de aceite para motor",
            current_stock=50,
            minimum_stock=10,
            last_purchase_price=12000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="FIL-002",
            name="Filtro de Aire",
            description="Filtro de aire para admisión",
            current_stock=40,
            minimum_stock=10,
            last_purchase_price=14000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="FIL-003",
            name="Filtro de Combustible",
            description="Filtro para sistema de inyección",
            current_stock=35,
            minimum_stock=8,
            last_purchase_price=11000,
            unit=Unit.UNIT,
            brand_id=brand_map["MANN-FILTER"].id,
            category_id=category_map["FILTERS"].id,
        ),

        # BRAKES
        Product(
            sku="BRA-001",
            name="Pastillas de Freno Delanteras",
            description="Juego de pastillas delanteras",
            current_stock=25,
            minimum_stock=5,
            last_purchase_price=28000,
            unit=Unit.UNIT,
            brand_id=brand_map["BREMBO"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="BRA-002",
            name="Disco de Freno Ventilado",
            description="Disco ventilado delantero",
            current_stock=15,
            minimum_stock=3,
            last_purchase_price=45000,
            unit=Unit.UNIT,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="BRA-003",
            name="Campana de Freno",
            description="Campana trasera",
            current_stock=12,
            minimum_stock=2,
            last_purchase_price=32000,
            unit=Unit.UNIT,
            brand_id=brand_map["BREMBO"].id,
            category_id=category_map["BRAKES"].id,
        ),

        # SUSPENSION
        Product(
            sku="SUS-001",
            name="Amortiguador Delantero",
            description="Amortiguador hidráulico",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=85000,
            unit=Unit.UNIT,
            brand_id=brand_map["SACHS"].id,
            category_id=category_map["SUSPENSION"].id,
        ),
        Product(
            sku="SUS-002",
            name="Amortiguador Trasero",
            description="Amortiguador trasero",
            current_stock=16,
            minimum_stock=4,
            last_purchase_price=79000,
            unit=Unit.UNIT,
            brand_id=brand_map["MONROE"].id,
            category_id=category_map["SUSPENSION"].id,
        ),
        Product(
            sku="SUS-003",
            name="Espiral Delantera",
            description="Resorte delantero",
            current_stock=10,
            minimum_stock=2,
            last_purchase_price=65000,
            unit=Unit.UNIT,
            brand_id=brand_map["KYB"].id,
            category_id=category_map["SUSPENSION"].id,
        ),

        # ENGINE
        Product(
            sku="ENG-001",
            name="Correa de Distribución",
            description="Kit de distribución",
            current_stock=20,
            minimum_stock=5,
            last_purchase_price=58000,
            unit=Unit.UNIT,
            brand_id=brand_map["AISIN"].id,
            category_id=category_map["ENGINE"].id,
        ),
        Product(
            sku="ENG-002",
            name="Bomba de Agua",
            description="Bomba de agua para motor",
            current_stock=12,
            minimum_stock=3,
            last_purchase_price=72000,
            unit=Unit.UNIT,
            brand_id=brand_map["AISIN"].id,
            category_id=category_map["ENGINE"].id,
        ),
        Product(
            sku="ENG-003",
            name="Junta de Tapa de Cilindros",
            description="Junta para tapa de válvulas",
            current_stock=30,
            minimum_stock=5,
            last_purchase_price=9000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["ENGINE"].id,
        ),

        # ELECTRICAL
        Product(
            sku="ELE-001",
            name="Bujía",
            description="Bujía estándar",
            current_stock=100,
            minimum_stock=20,
            last_purchase_price=5000,
            unit=Unit.UNIT,
            brand_id=brand_map["NGK"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),
        Product(
            sku="ELE-002",
            name="Bobina de Encendido",
            description="Bobina electrónica",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=42000,
            unit=Unit.UNIT,
            brand_id=brand_map["DENSO"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),
        Product(
            sku="ELE-003",
            name="Alternador",
            description="Alternador 12V",
            current_stock=8,
            minimum_stock=2,
            last_purchase_price=120000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),

        # LUBRICANTS
        Product(
            sku="LUB-001",
            name="Aceite Sintético 5W30",
            description="Lubricante sintético",
            current_stock=80,
            minimum_stock=20,
            last_purchase_price=18000,
            unit=Unit.LITER,
            brand_id=brand_map["ACDELCO"].id,
            category_id=category_map["LUBRICANTS"].id,
        ),
        Product(
            sku="LUB-002",
            name="Líquido de Frenos DOT4",
            description="Fluido hidráulico",
            current_stock=50,
            minimum_stock=10,
            last_purchase_price=8000,
            unit=Unit.LITER,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["LUBRICANTS"].id,
        ),

        # COOLING
        Product(
            sku="COL-001",
            name="Radiador",
            description="Radiador de aluminio",
            current_stock=6,
            minimum_stock=2,
            last_purchase_price=140000,
            unit=Unit.UNIT,
            brand_id=brand_map["VALEO"].id,
            category_id=category_map["COOLING"].id,
        ),
        Product(
            sku="COL-002",
            name="Termostato",
            description="Válvula termostática",
            current_stock=20,
            minimum_stock=5,
            last_purchase_price=16000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["COOLING"].id,
        ),

        # STEERING
        Product(
            sku="STE-001",
            name="Terminal de Dirección",
            description="Terminal exterior",
            current_stock=24,
            minimum_stock=5,
            last_purchase_price=21000,
            unit=Unit.UNIT,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["STEERING"].id,
        ),
        Product(
            sku="STE-002",
            name="Rótula Inferior",
            description="Rótula suspensión",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=23000,
            unit=Unit.UNIT,
            brand_id=brand_map["SKF"].id,
            category_id=category_map["STEERING"].id,
        ),

        # BATTERIES
        Product(
            sku="BAT-001",
            name="Batería 12V 65Ah",
            description="Batería libre mantenimiento",
            current_stock=15,
            minimum_stock=3,
            last_purchase_price=125000,
            unit=Unit.UNIT,
            brand_id=brand_map["ACDELCO"].id,
            category_id=category_map["BATTERIES"].id,
        ),

        # LIGHTING
        Product(
            sku="LIG-001",
            name="Lámpara H4",
            description="Lámpara halógena",
            current_stock=60,
            minimum_stock=10,
            last_purchase_price=7000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["LIGHTING"].id,
        ),

        # WIPERS
        Product(
            sku="WIP-001",
            name="Escobilla Limpiaparabrisas",
            description="Escobilla universal",
            current_stock=40,
            minimum_stock=10,
            last_purchase_price=12000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["WIPERS"].id,
        ),

        # SENSORS
        Product(
            sku="SEN-001",
            name="Sensor ABS",
            description="Sensor rueda ABS",
            current_stock=14,
            minimum_stock=3,
            last_purchase_price=38000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["SENSORS"].id,
        ),
        Product(
            sku="SEN-002",
            name="Sensor de Oxígeno",
            description="Sonda lambda",
            current_stock=10,
            minimum_stock=2,
            last_purchase_price=55000,
            unit=Unit.UNIT,
            brand_id=brand_map["DENSO"].id,
            category_id=category_map["SENSORS"].id,
        ),

        # CHINAS
        Product(
            sku="CHI-001",
            name="Filtro de Aire Chery Tiggo",
            description="Filtro para SUV",
            current_stock=22,
            minimum_stock=5,
            last_purchase_price=13000,
            unit=Unit.UNIT,
            brand_id=brand_map["TIGGO PARTS"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="CHI-002",
            name="Pastillas de Freno Great Wall",
            description="Juego delantero",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=24000,
            unit=Unit.UNIT,
            brand_id=brand_map["GREAT WALL PARTS"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="CHI-003",
            name="Bobina de Encendido BYD",
            description="Sistema de encendido",
            current_stock=12,
            minimum_stock=3,
            last_purchase_price=39000,
            unit=Unit.UNIT,
            brand_id=brand_map["BYD AUTO PARTS"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),
    ]