from app.domain.enums.pruduct_unit import Unit
from app.domain.entities.product import Product


def build_products(category_map: dict, brand_map: dict) -> list[Product]:
    return [
        # FILTERS
        Product(
            sku="FIL-001",
            name="Oil Filter",
            description="Engine oil filter",
            current_stock=10,
            minimum_stock=25,
            last_purchase_price=12000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="FIL-002",
            name="Air Filter",
            description="Intake air filter",
            current_stock=40,
            minimum_stock=10,
            last_purchase_price=14000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="FIL-003",
            name="Fuel Filter",
            description="Fuel injection system filter",
            current_stock=10,
            minimum_stock=15,
            last_purchase_price=11000,
            unit=Unit.UNIT,
            brand_id=brand_map["MANN-FILTER"].id,
            category_id=category_map["FILTERS"].id,
        ),

        # BRAKES
        Product(
            sku="BRA-001",
            name="Front Brake Pads",
            description="Front brake pad set",
            current_stock=25,
            minimum_stock=5,
            last_purchase_price=28000,
            unit=Unit.UNIT,
            brand_id=brand_map["BREMBO"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="BRA-002",
            name="Vented Brake Disc",
            description="Front vented brake disc",
            current_stock=15,
            minimum_stock=3,
            last_purchase_price=45000,
            unit=Unit.UNIT,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="BRA-003",
            name="Brake Drum",
            description="Rear brake drum",
            current_stock=12,
            minimum_stock=2,
            last_purchase_price=32000,
            unit=Unit.UNIT,
            brand_id=brand_map["BREMBO"].id,
            category_id=category_map["BRAKES"].id,
        ),

        # SUSPENSION
        Product(
            sku="SUS-001",
            name="Front Shock Absorber",
            description="Hydraulic shock absorber",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=85000,
            unit=Unit.UNIT,
            brand_id=brand_map["SACHS"].id,
            category_id=category_map["SUSPENSION"].id,
        ),
        Product(
            sku="SUS-002",
            name="Rear Shock Absorber",
            description="Rear shock absorber",
            current_stock=16,
            minimum_stock=4,
            last_purchase_price=79000,
            unit=Unit.UNIT,
            brand_id=brand_map["MONROE"].id,
            category_id=category_map["SUSPENSION"].id,
        ),
        Product(
            sku="SUS-003",
            name="Front Coil Spring",
            description="Front suspension spring",
            current_stock=10,
            minimum_stock=2,
            last_purchase_price=65000,
            unit=Unit.UNIT,
            brand_id=brand_map["KYB"].id,
            category_id=category_map["SUSPENSION"].id,
        ),

        # ENGINE
        Product(
            sku="ENG-001",
            name="Timing Belt Kit",
            description="Complete timing kit",
            current_stock=20,
            minimum_stock=5,
            last_purchase_price=58000,
            unit=Unit.UNIT,
            brand_id=brand_map["AISIN"].id,
            category_id=category_map["ENGINE"].id,
        ),
        Product(
            sku="ENG-002",
            name="Water Pump",
            description="Engine water pump",
            current_stock=5,
            minimum_stock=5,
            last_purchase_price=72000,
            unit=Unit.UNIT,
            brand_id=brand_map["AISIN"].id,
            category_id=category_map["ENGINE"].id,
        ),
        Product(
            sku="ENG-003",
            name="Valve Cover Gasket",
            description="Cylinder head cover gasket",
            current_stock=30,
            minimum_stock=5,
            last_purchase_price=9000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["ENGINE"].id,
        ),

        # ELECTRICAL
        Product(
            sku="ELE-001",
            name="Spark Plug",
            description="Standard spark plug",
            current_stock=100,
            minimum_stock=20,
            last_purchase_price=5000,
            unit=Unit.UNIT,
            brand_id=brand_map["NGK"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),
        Product(
            sku="ELE-002",
            name="Ignition Coil",
            description="Electronic ignition coil",
            current_stock=7,
            minimum_stock=10,
            last_purchase_price=42000,
            unit=Unit.UNIT,
            brand_id=brand_map["DENSO"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),
        Product(
            sku="ELE-003",
            name="Alternator",
            description="12V alternator",
            current_stock=8,
            minimum_stock=2,
            last_purchase_price=120000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),

        # LUBRICANTS
        Product(
            sku="LUB-001",
            name="Synthetic Oil 5W30",
            description="Full synthetic lubricant",
            current_stock=80,
            minimum_stock=20,
            last_purchase_price=18000,
            unit=Unit.LITER,
            brand_id=brand_map["ACDELCO"].id,
            category_id=category_map["LUBRICANTS"].id,
        ),
        Product(
            sku="LUB-002",
            name="Brake Fluid DOT4",
            description="Hydraulic brake fluid",
            current_stock=50,
            minimum_stock=10,
            last_purchase_price=8000,
            unit=Unit.LITER,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["LUBRICANTS"].id,
        ),

        # COOLING
        Product(
            sku="COL-001",
            name="Radiator",
            description="Aluminum radiator",
            current_stock=5,
            minimum_stock=10,
            last_purchase_price=140000,
            unit=Unit.UNIT,
            brand_id=brand_map["VALEO"].id,
            category_id=category_map["COOLING"].id,
        ),
        Product(
            sku="COL-002",
            name="Thermostat",
            description="Thermostatic valve",
            current_stock=20,
            minimum_stock=5,
            last_purchase_price=16000,
            unit=Unit.UNIT,
            brand_id=brand_map["MAHLE"].id,
            category_id=category_map["COOLING"].id,
        ),

        # STEERING
        Product(
            sku="STE-001",
            name="Steering Tie Rod End",
            description="Outer tie rod end",
            current_stock=24,
            minimum_stock=5,
            last_purchase_price=21000,
            unit=Unit.UNIT,
            brand_id=brand_map["TRW"].id,
            category_id=category_map["STEERING"].id,
        ),
        Product(
            sku="STE-002",
            name="Lower Ball Joint",
            description="Suspension ball joint",
            current_stock=13,
            minimum_stock=15,
            last_purchase_price=23000,
            unit=Unit.UNIT,
            brand_id=brand_map["SKF"].id,
            category_id=category_map["STEERING"].id,
        ),

        # BATTERIES
        Product(
            sku="BAT-001",
            name="Battery 12V 65Ah",
            description="Maintenance-free battery",
            current_stock=10,
            minimum_stock=50,
            last_purchase_price=125000,
            unit=Unit.UNIT,
            brand_id=brand_map["ACDELCO"].id,
            category_id=category_map["BATTERIES"].id,
        ),

        # LIGHTING
        Product(
            sku="LIG-001",
            name="H4 Bulb",
            description="Halogen headlight bulb",
            current_stock=60,
            minimum_stock=10,
            last_purchase_price=7000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["LIGHTING"].id,
        ),

        # WIPERS
        Product(
            sku="WIP-001",
            name="Windshield Wiper Blade",
            description="Universal wiper blade",
            current_stock=40,
            minimum_stock=10,
            last_purchase_price=12000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["WIPERS"].id,
        ),

        # SENSORS
        Product(
            sku="SEN-001",
            name="ABS Sensor",
            description="Wheel speed ABS sensor",
            current_stock=14,
            minimum_stock=3,
            last_purchase_price=38000,
            unit=Unit.UNIT,
            brand_id=brand_map["BOSCH"].id,
            category_id=category_map["SENSORS"].id,
        ),
        Product(
            sku="SEN-002",
            name="Oxygen Sensor",
            description="Lambda probe sensor",
            current_stock=10,
            minimum_stock=2,
            last_purchase_price=55000,
            unit=Unit.UNIT,
            brand_id=brand_map["DENSO"].id,
            category_id=category_map["SENSORS"].id,
        ),

        # CHINESE BRANDS
        Product(
            sku="CHI-001",
            name="Chery Tiggo Air Filter",
            description="Air filter for SUV",
            current_stock=22,
            minimum_stock=5,
            last_purchase_price=13000,
            unit=Unit.UNIT,
            brand_id=brand_map["TIGGO PARTS"].id,
            category_id=category_map["FILTERS"].id,
        ),
        Product(
            sku="CHI-002",
            name="Great Wall Brake Pads",
            description="Front brake pad set",
            current_stock=18,
            minimum_stock=4,
            last_purchase_price=24000,
            unit=Unit.UNIT,
            brand_id=brand_map["GREAT WALL PARTS"].id,
            category_id=category_map["BRAKES"].id,
        ),
        Product(
            sku="CHI-003",
            name="BYD Ignition Coil",
            description="Ignition system coil",
            current_stock=12,
            minimum_stock=3,
            last_purchase_price=39000,
            unit=Unit.UNIT,
            brand_id=brand_map["BYD AUTO PARTS"].id,
            category_id=category_map["ELECTRICAL"].id,
        ),

        # TIRES
        Product(
            sku="TIR-001",
            name="All-Season Tire 185/65 R15",
            description="All-season passenger tire",
            current_stock=20,
            minimum_stock=8,
            last_purchase_price=95000,
            unit=Unit.UNIT,
            brand_id=brand_map["BRIDGESTONE"].id,
            category_id=category_map["WHEELS_AND_TIRES"].id,
        ),
        Product(
            sku="TIR-002",
            name="Performance Tire 205/55 R16",
            description="High-performance summer tire",
            current_stock=16,
            minimum_stock=6,
            last_purchase_price=115000,
            unit=Unit.UNIT,
            brand_id=brand_map["MICHELIN"].id,
            category_id=category_map["WHEELS_AND_TIRES"].id,
        ),
        Product(
            sku="TIR-003",
            name="SUV Tire 235/65 R17",
            description="All-terrain SUV tire",
            current_stock=12,
            minimum_stock=4,
            last_purchase_price=130000,
            unit=Unit.UNIT,
            brand_id=brand_map["GOODYEAR"].id,
            category_id=category_map["WHEELS_AND_TIRES"].id,
        ),
    ]