from app.domain.entities.supplier import Supplier


def build_suppliers() -> list[Supplier]:
    return [
        Supplier(
            name="BOSCH",
            email="sales@bosch-argentina.com.ar",
            phone="+54 11 4717-0000",
            address="Av. del Libertador 6250, Piso 8",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-52828797-1",
        ),
        Supplier(
            name="PIRELLI",
            email="sales@pirelli.com.py",
            phone="+595 21 610-4400",
            address="Av. Mcal. López 3794",
            locality="Asunción",
            nationality="Paraguay",
            tax_id="80-0012345-6",
        ),
        Supplier(
            name="SKF",
            email="sales@skf-latam.com",
            phone="+54 11 4773-2200",
            address="Av. Córdoba 1345, Piso 3",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-68493021-4",
        ),
        Supplier(
            name="MAHLE",
            email="sales@mahle-argentina.com.ar",
            phone="+54 341 439-8800",
            address="Av. Presidente Perón 4200",
            locality="Rosario",
            nationality="Argentina",
            tax_id="30-57412689-3",
        ),
        Supplier(
            name="MANN-FILTER",
            email="sales@mann-filter.com.ar",
            phone="+54 11 4585-7700",
            address="Ruta Panamericana Km 37.5",
            locality="Garín",
            nationality="Argentina",
            tax_id="30-71238940-7",
        ),
        Supplier(
            name="VALEO",
            email="sales@valeo-argentina.com.ar",
            phone="+54 11 4340-9100",
            address="Av. Leandro N. Alem 928, Piso 5",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-63849201-2",
        ),
        Supplier(
            name="BREMBO",
            email="sales@brembo-latam.com",
            phone="+54 11 4891-3300",
            address="Av. San Martín 1942",
            locality="Córdoba",
            nationality="Argentina",
            tax_id="30-59274830-9",
        ),
        Supplier(
            name="SACHS",
            email="sales@sachs-argentina.com.ar",
            phone="+54 351 468-2200",
            address="Av. Colón 3560",
            locality="Córdoba",
            nationality="Argentina",
            tax_id="30-74920138-5",
        ),
        Supplier(
            name="MONROE",
            email="sales@monroe-latam.com",
            phone="+54 11 4742-6600",
            address="Ruta 8 Km 61",
            locality="Luján",
            nationality="Argentina",
            tax_id="30-48312790-6",
        ),
        Supplier(
            name="TRW",
            email="sales@trw-argentina.com.ar",
            phone="+54 11 5280-4400",
            address="Av. Juan B. Justo 4823",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-61738294-8",
        ),
        Supplier(
            name="NGK",
            email="sales@ngk-latam.com",
            phone="+54 11 4783-9900",
            address="Av. Independencia 2750, Piso 2",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-55692047-1",
        ),
        Supplier(
            name="DENSO",
            email="sales@denso-argentina.com.ar",
            phone="+54 11 4394-7700",
            address="Maipú 942, Piso 7",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-72384901-3",
        ),
        Supplier(
            name="AISIN",
            email="sales@aisin-latam.com",
            phone="+54 11 4515-3300",
            address="Av. Rivadavia 8120",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-49017385-2",
        ),
        Supplier(
            name="ACDELCO",
            email="sales@acdelco-argentina.com.ar",
            phone="+54 11 4820-1100",
            address="Av. del Trabajo 6540",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-66173829-7",
        ),
        Supplier(
            name="DELPHI",
            email="sales@delphi-argentina.com.ar",
            phone="+54 351 472-5500",
            address="Av. Vélez Sársfield 3450",
            locality="Córdoba",
            nationality="Argentina",
            tax_id="30-53902847-4",
        ),
        Supplier(
            name="FEBI BILSTEIN",
            email="sales@febi-latam.com",
            phone="+54 11 4703-8800",
            address="Av. Santa Fe 2750, Piso 4",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-78234019-6",
        ),
        Supplier(
            name="KYB",
            email="sales@kyb-argentina.com.ar",
            phone="+54 11 4638-4400",
            address="Av. Mitre 2380",
            locality="Avellaneda",
            nationality="Argentina",
            tax_id="30-41938720-5",
        ),
        Supplier(
            name="BRIDGESTONE",
            email="sales@bridgestone.com.ar",
            phone="+54 11 4341-8000",
            address="Av. del Libertador 2442, Piso 6",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-58729034-1",
        ),
        Supplier(
            name="MICHELIN",
            email="sales@michelin-argentina.com.ar",
            phone="+54 11 4819-7200",
            address="Av. Eduardo Madero 1020, Piso 9",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-64910238-8",
        ),
        Supplier(
            name="GOODYEAR",
            email="sales@goodyear.com.ar",
            phone="+54 11 4346-3900",
            address="Av. del Libertador 5926, Piso 3",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-50182739-2",
        ),
        Supplier(
            name="GREAT WALL PARTS",
            email="sales@gwmparts.com.ar",
            phone="+54 11 4523-6600",
            address="Av. Vélez Sársfield 1248",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-83049172-9",
        ),
        Supplier(
            name="BYD AUTO PARTS",
            email="sales@bydparts.com.ar",
            phone="+54 11 4780-2200",
            address="Av. Cabildo 2550, Piso 2",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-76193048-3",
        ),
        Supplier(
            name="TIGGO PARTS",
            email="sales@tiggoparts.com.ar",
            phone="+54 11 4612-8800",
            address="Av. Rivadavia 11340",
            locality="Buenos Aires",
            nationality="Argentina",
            tax_id="30-91827304-6",
        ),
    ]